# Domain configuration
domains:
  frontend: "staging.3assasa.software"
  api: "api-staging.3assasa.software"

# Database configuration (from Terraform outputs)
database:
  host: "{{ staging_db_host }}"
  port: 5432
  name: "delivery_tracker_staging"

# Application configuration
app_config:
  debug: yes
  log_level: "DEBUG"
  cors_origins:
    - "https://staging.3assasa.software"
    - "http://localhost:4200"
  jwt_secret: "{{ vault_staging_jwt_secret }}"

# Container images (use staging tags)
containers:
  frontend:
    image: "registry.digitalocean.com/3assasa/frontend:staging"
    port: 80
    replicas: 1
  backend:
    image: "registry.digitalocean.com/3assasa/backend:staging"
    port: 8080
    replicas: 1
    health_check:
      path: "/health"
      interval: 30s
      timeout: 10s
      retries: 3

# Resource limits (staging - conservative)
resource_limits:
  frontend:
    memory: "512m"
    cpus: "0.5"
  backend:
    memory: "1g"
    cpus: "1.0"

# SSL configuration
ssl_config:
  enabled: yes
  staging: yes  # Use Let's Encrypt staging
  email: "admin@3assasa.software"

# Backup configuration
backup_config:
  enabled: yes
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention: 7          # days

# Monitoring
monitoring_config:
  enabled: yes
  alert_email: "alerts@3assasa.software"
  slack_webhook: "{{ vault_staging_slack_webhook }}"
