- name: reload systemd
  systemd:
    daemon_reload: yes

- name: start node_exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted