# Domain configuration
domains:
  frontend: "3assasa.software"
  api: "api.3assasa.software"

# Database configuration (from Terraform outputs)
database:
  host: "{{ production_db_host }}"
  port: 5432
  name: "delivery_tracker_production"
  pool_size: 20

# Application configuration
app_config:
  debug: no
  log_level: "INFO"
  cors_origins:
    - "https://3assasa.software"
    - "https://www.3assasa.software"
  jwt_secret: "{{ vault_production_jwt_secret }}"
  session_timeout: 3600

# Container images (use production/latest tags)
containers:
  frontend:
    image: "registry.digitalocean.com/3assasa/frontend:latest"
    port: 80
    replicas: 2
  backend:
    image: "registry.digitalocean.com/3assasa/backend:latest"
    port: 8080
    replicas: 2
    health_check:
      path: "/health"
      interval: 15s
      timeout: 5s
      retries: 5

# Resource limits (production - optimized)
resource_limits:
  frontend:
    memory: "2g"
    cpus: "2.0"
  backend:
    memory: "4g"
    cpus: "4.0"

# SSL configuration
ssl_config:
  enabled: yes
  staging: no # Use Let's Encrypt production
  email: "admin@3assasa.software"
  hsts_enabled: yes
  redirect_http: yes

# Backup configuration
backup_config:
  enabled: yes
  schedule: "0 1 * * *" # Daily at 1 AM
  retention: 30        # days
  encryption: yes

# Monitoring
monitoring_config:
  enabled: yes
  alert_email: "alerts@3assasa.software"
  pager_duty_key: "{{ vault_pagerduty_key }}"
  slack_webhook: "{{ vault_production_slack_webhook }}"

# Performance tuning
performance:
  nginx:
    worker_processes: auto
    worker_connections: 1024
    keepalive_timeout: 65
    client_max_body_size: "10m"

# Security hardening
security_hardening:
  enable_csp: yes
  enable_hsts: yes
  hide_server_version: yes
  rate_limiting:
    enabled: yes
    requests_per_minute: 100