all:
  children:
    staging:
      children:
        staging_bastion:
          hosts:
            staging-bastion:
              ansible_host: "142.93.168.88"
              role: bastion
              env_name: staging
        staging_frontend:
          hosts:
            staging-frontend:
              ansible_host: staging.3assasa.software
              role: frontend
              env_name: staging
        staging_backend:
          hosts:
            staging-backend:
              ansible_host: "10.114.16.7"
              ansible_ssh_common_args: '-o ProxyJump=root@142.93.168.88'
              role: backend
              env_name: staging
              
    production:
      children:
        production_bastion:
          hosts:
            production-bastion:
              ansible_host: "139.59.214.218"
              role: bastion
              env_name: production
        production_frontend:
          hosts:
            production-frontend:
              ansible_host: 3assasa.software
              role: frontend
              env_name: production
        production_backend:
          hosts:
            production-backend:
              ansible_host: "10.114.16.3"
              ansible_ssh_common_args: '-o ProxyJump=root@139.59.214.218'
              role: backend
              env_name: production

    # Group definitions
    bastion:
      children:
        - staging_bastion
        - production_bastion
        
    frontend:
      children:
        - staging_frontend
        - production_frontend
        
    backend:
      children:
        - staging_backend
        - production_backend
        
    app_servers:
      children:
        - frontend
        - backend