# inventories/static.yml - Alternative static inventory
# Use this if the Terraform plugin continues to have issues

all:
  children:
    staging:
      children:
        staging_bastion:
          hosts:
            staging-bastion:
              ansible_host: "{{ staging_bastion_ip }}"  # Replace with actual IP
              role: bastion
              env_name: staging
        staging_frontend:
          hosts:
            staging-frontend:
              ansible_host: staging.3assasa.software
              role: frontend
              env_name: staging
        staging_backend:
          hosts:
            staging-backend:
              ansible_host: "{{ staging_backend_private_ip }}"  # Replace with actual private IP
              ansible_ssh_common_args: '-o ProxyJump=root@{{ staging_bastion_ip }}'
              role: backend
              env_name: staging
              
    production:
      children:
        production_bastion:
          hosts:
            production-bastion:
              ansible_host: "{{ production_bastion_ip }}"  # Replace with actual IP
              role: bastion
              env_name: production
        production_frontend:
          hosts:
            production-frontend:
              ansible_host: 3assasa.software
              role: frontend
              env_name: production
        production_backend:
          hosts:
            production-backend:
              ansible_host: "{{ production_backend_private_ip }}"  # Replace with actual private IP
              ansible_ssh_common_args: '-o ProxyJump=root@{{ production_bastion_ip }}'
              role: backend
              env_name: production

    # Group definitions
    bastion:
      children:
        - staging_bastion
        - production_bastion
        
    frontend:
      children:
        - staging_frontend
        - production_frontend
        
    backend:
      children:
        - staging_backend
        - production_backend
        
    app_servers:
      children:
        - frontend
        - backend

  vars:
    # Replace these with actual values from your Terraform outputs
    staging_bastion_ip: "YOUR_STAGING_BASTION_IP"
    staging_backend_private_ip: "YOUR_STAGING_BACKEND_PRIVATE_IP"
    production_bastion_ip: "YOUR_PRODUCTION_BASTION_IP"
    production_backend_private_ip: "YOUR_PRODUCTION_BACKEND_PRIVATE_IP"